wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1682021929.921026
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
noise_sigma:
  desc: null
  value: 0.2
noise_theta:
  desc: null
  value: 0.15
