wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 128
BUFFER_SIZE:
  desc: null
  value: 256000
GAMMA:
  desc: null
  value: 0.99
LR_ACTOR:
  desc: null
  value: 0.0001
LR_CRITIC:
  desc: null
  value: 0.0001
TAU:
  desc: null
  value: 0.001
WEIGHT_DECAY:
  desc: null
  value: 1.0e-09
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1682229287.241701
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.0
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
actor:
  desc: null
  value: Actor
critic:
  desc: null
  value: CriticW
noise_mu:
  desc: null
  value: 0.0
noise_sigma:
  desc: null
  value: 0.2
noise_theta:
  desc: null
  value: 0.15
