wandb_version: 1

BATCH_SIZE:
  desc: null
  value:
  - 256
  - 64
BUFFER_SIZE:
  desc: null
  value:
  - 256000.0
  - 1280000.0
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1682031183.357778
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.0
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
